---
title: "CV"
author: "Eric J. Ward"
bibliography: myCV.bib
output:
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
  html_document: default
  word_document: default
email: eric.ward@noaa.gov
fontawesome: no
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
geometry: margin=1in
jobtitle: 
keywords: R Markdown, academic CV, template
linkcolor: blue
csl: journal-of-applied-ecology.csl
phone: 206-302-1745
address: Northwest Fisheries Science Center · 2725 Montlake Blvd E · Seattle, WA
updated: no
urlcolor: blue
web: ericward-noaa.github.io
---

# Education

*University of Washington*, Ph.D. Aquatic and Fishery Sciences \hfill 2003-2006
\newline - *Committee:* Ray Hilborn (advisor), Andre Punt, Tim Essington

*Montana State University*, MSc Biology \hfill 2000-2003
\newline - *Advisor:* Dan Goodman

*University of California San Diego*, BSc Ecology and Evolution \hfill 1995-1999

# Employment

*Statistican* Northwest Fisheries Science Center, NMFS (NOAA) \hfill 2009 - present

*Affiliate Associate Professor* University of Washington (SAFS) \hfill 2013 - present

*Post-doctoral researcher* National Research Council \hfill 2007 - 2008

*Stock assessment scientist* Wellington, New Zealand \hfill Spring 2005

*Graduate research assistant* University of Washington \hfill 2003 - 2006

# Journal Articles (peer - reviewed)

```{r echo = FALSE, results='asis', comment=NA, warning=FALSE, message=FALSE}
library(RefManageR)
BibOptions(restore.defaults = TRUE)
biblio = ReadBib(file = "myCV.bib")

BibOptions(sorting = "ydnt", match.date = 'year.month')
biblio = sort(biblio, decreasing = TRUE)

# overwrite default sorting, to sort by year and month
df = data.frame(years = rep(NA, length(biblio)),
months = rep(NA, length(biblio)))
for(i in 1:nrow(df)) {
  df$years[i] = biblio[[i]]$year
  if(!is.null(biblio[[i]]$month)) {
    df$months[i] = biblio[[i]]$month
  }
}
df$months = match(df$months, c("jan","feb","mar","apr","may","jun",
  "jul","aug","sep","oct","nov","dec"))
df$order = 1:nrow(df)
for(y in unique(df$years)) {
  indx = which(df$years==y)
  df$order[indx] = df$order[indx][sort(df$months[indx], index.return=TRUE)$ix]
}
biblio = biblio[[df$order]]

parse_authors = function(s) {
  # first author
  s_init = strsplit(as.character(s[[1]]), " ")[[1]]
  s_init_last = s_init[length(s_init)]
  s_init_str = paste0(s_init_last, ", ")
  for(i in 1:(length(s_init)-1)) {
    s_init_str = paste0(s_init_str, substr(s_init[i],1,1), ".")
  }
  if(s_init_last == "Ward" & substr(s_init[1],1,1) == "E") {
    s_init_str = paste0("**",s_init_str,"**")
  } 
  s_str = s_init_str
  
  if(length(s) > 1) {
    # multiple authors
    for(j in 2:length(s)) {
      # parse name first
      s_init = strsplit(as.character(s[[j]]), " ")[[1]]
      s_init_last = s_init[length(s_init)]
      s_init_str = ""
      for(i in 1:(length(s_init)-1)) {
        s_init_str = paste0(s_init_str, substr(s_init[i],1,1), ".")
      }
      s_init_str = paste0(s_init_str, " ", s_init_last)
      if(s_init_last == "Ward" & substr(s_init[[1]],1,1) == "E") {
        s_init_str = paste0("**",s_init_str,"**")
      } 
      s_str = ifelse(j != length(s), paste0(s_str, ", ", s_init_str),
      paste0(s_str, ", and ", s_init_str))
    }
  }
  return(s_str)
}

parse_title = function(s) {
  # remove bibtex formats
  s = gsub("\\textendash{}", "-", s, fixed=TRUE)
  words = strsplit(s, " ")[[1]]
  str = words[1]
  for(i in 2:length(words)) {
    words[i] = tolower(words[i])
    str = paste(str, words[i])
  }
  # find locations of words' first characters
  init_pos = as.numeric(gregexpr(" ", str, fixed=TRUE)[[1]]) + 1
  # also include words right in a bracket
  init_pos = c(init_pos, as.numeric(gregexpr("{{", str, fixed=TRUE)[[1]]) + 2)
  # find locations of brackets. any words in this range are in caps
  bracket_pos = cbind(as.numeric(gregexpr("{{", str, fixed=TRUE)[[1]]),
    as.numeric(gregexpr("}}", str, fixed=TRUE)[[1]]))
  for(i in 1:nrow(bracket_pos)) {
    for(j in 1:length(init_pos)) {
      if(init_pos[j] > as.numeric(bracket_pos[i,1]) & init_pos[j] < as.numeric(bracket_pos[i,2])) {
        beg = substr(str, 1, init_pos[j]-1)
        mid = substr(str, init_pos[j], init_pos[j])
        end = substr(str, init_pos[j]+1, nchar(str))
        str = paste0(beg,toupper(mid),end)
      }
    }
  }
  
  # remove curly brackets from string
  str = gsub("\\{", "", str)
  str = gsub("\\}", "", str)
  return(str)
}

# Write script to parse bib file into individual entries. These include author list, year, title, journal, volume, pages, doi
for(n in length(biblio):1) {
  # $author, $year, $title, $volume, $pages, $doi
  # parse author list
  author_str = parse_authors(biblio[[n]]$author)
  n_i = n
  title_str = parse_title(biblio[[n]]$title)
  
  doi_str = biblio[[n]]$doi
  doi_str = ifelse(is.null(doi_str), "", paste0("[link](http://dx.doi.org/",biblio[[n]]$doi,")"))
  author_per = paste0(author_str, ". ")
  if(author_str == "**Ward, E.J.**") author_per = "**Ward, E.J. **"
  ref = paste0(">",n_i,". ", author_per, 
    biblio[[n]]$year, ". ", title_str, ". ",
    "*", biblio[[n]]$journal, "*, ", biblio[[n]]$volume, ":",
    biblio[[n]]$pages, ". ", doi_str, "\n \n")

  cat(ref)
}

```

# Technical Reports

>32. **Ward, E.J.** and W. Satterthwaite. 2020. Power analyses for Southern Resident killer whale demographic modeling. Report to West coast regional office, July 2020.

>31. ICES. 2020. ICES Workshop on unavoidable survey effort reduction (WKUSER). ICES Scientific Reports. 2:72. 92pp. http://doi.org/10.17895/ices.pub.7453

>30. Pacific Fishery Management Council Salmon Fishery Management Plan Impacts to Southern Resident Killer Whales: Alternatives and Recommendations. 2020. Ad-Hoc Southern Resident Killer Whale Workgroup, 20 pp. [link](https://www.pcouncil.org/documents/2020/08/h-3-a-srkw-workgroup-report-1-pacific-fishery-management-council-salmon-fishery-management-plan-impacts-to-southern-resident-killer-whales-draft-range-of-alternatives-and-recommendations.pdf/)

>29. Pacific Fishery Management Council Salmon Fishery Management Plan Impacts to Southern Resident Killer Whales: Risk Assessment. 2020. Ad-Hoc Southern Resident Killer Whale Workgroup, 165 pp. [link](https://www.pcouncil.org/documents/2020/05/e-2-srkw-workgroup-report-1-pacific-fishery-management-council-salmon-fishery-management-plan-impacts-to-southern-resident-killer-whales-risk-assessment-electronic-only.pdf/).

>28. Jefferson, T.A., M.A. Smultea, **E.J. Ward**, and B. Berejekian. 2020. Harbor seal (Phoca vitulina richardii) stock size in the inland waters of Washington state: A novel approach. Puget Sound Partnership Scientific Research, Salish Sea Marine Survival Project. 

>27. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2019 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>26. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2019 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>25. Srinivasan, M., S.K. Brown, E. Markowitz, M. Soldevilla, E. Patterson, K. Forney, K. Murray, E. Ward, J.M. Ver Hoef, J. Redfern, and T. Eguchi. 2019. Proceedings of the 2nd National Protected Species Assessment Workshop. U.S. Dept. of Commer., NOAA. NOAA Technical Memorandum NMFS-F/SPO-198, 52 p. [link](https://spo.nmfs.noaa.gov/sites/default/files/TMSPO198.pdf)

>24. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2018 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>23. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2018 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>22. Eguchi, T., C. Fahy, J. Jannot, K. Somers, and **E. Ward**. 2019. 2018 Leatherback sea turtle estimated bycatch reporting requirements as set out in the NMFS Biological Opinion for the continuing authorization of the Pacific Coast groundfish fisheries. National Marine Fisheries Service, SWFSC, La Jolla, CA 92039. [link](https://www.pcouncil.org/wp-content/uploads/2019/05/I4a_NMFS_Rpt5_ELEC_ONLY_DRAFT-Leatherback_Turtle_rpt_JUNE2019BB.pdf)

>21. Good, T. P., **E. Ward**, J. Jannot, R. Shama, and J. McVeigh. 2019. Observed and Estimated Bycatch of Short-tailed Albatross in U.S. West Coast Groundfish Fisheries 2002-2017. National Marine Fisheries Service, NWFSC, 2725 Montlake Blvd E., Seattle, WA 98112. [link](https://www.pcouncil.org/wp-content/uploads/2019/05/I4a_NMFS_RPT6_ELEC_ONLY_DRAFT_STAL_bycatch_rpt_JUNE2019BB.pdf)

>20. Harvey, C.J., N. Garfield, G.D. Williams, N. Tolimieri, E.L. Hazen, I.D. Schroeder, K.S. Andrews, C. Barceló, K. Barnas, S.J. Bograd, R.D. Brodeur, B.J. Burke, J.M. Cope, L. deWitt, J.C. Field, J.L. Fisher, T.P. Good, C.M. Greene, D.S. Holland, M.E. Hunsicker, M. Jacox, S. Kasperski, S.J. Kim, A. Leising, S.R. Melin, C.A. Morgan, B. Muhling, S.H. Munsch, K. Norman, W.T. Peterson, M.R. Poe, J.F. Samhouri, W.J. Sydeman, J.Thayer, A.R. Thompson, A. Varney, B.K. Wells, T.H. Williams, J.E. Zamon, D. Lawson, S.C. Anderson, J. Gao, M.A. Litzow, S. McClatchie, **E.J. Ward**, S. Zador. Ecosystem status report of the California Current for 2018: a summary of ecosystem indicators compiled by the California Current Integrated Ecosystem Assessment team (CCIEA). U.S. Department of Commerce, NOAA. NOAA Technical Memorandum NMFS-NWFSC-145. [link](https://doi.org/10.25923/mvhf-yk36)

>19. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2017 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>18. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2017 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>17. Ferguson, L., M. Srinivasan, E. Oleson, S. Hayes, S.K. Brown, R. Angliss, J. Carretta, E. Holmes, **E.J. Ward**, J. Kocik, K. Mullin, R. Dean, and J. Davis (eds.). 2017. Proceedings of the First National Protected Species Assessment Workshop. U.S. Dept. of Commer., NOAA. NOAA Technical Memorandum NMFS-F/SPO-172, 92 p. [link](http://spo.nmfs.noaa.gov/sites/default/files/TMSPO172.pdf)

>16. Hanson, M.B., **E.J. Ward**, C.K. Emmons, M.M. Holt, and D.M. Holzer. 2017. Assessing the movements and occurrence of Southern Resident Killer Whales relative to the U.S. Navy’s Northwest Training Range Complex in the Pacific Northwest. Prepared for: U.S. Navy, U.S. Pacific Fleet, Pearl Harbor, HI. Prepared by: National Oceanic and Atmospheric Administration, Northwest Fisheries Science Center under MIPR N00070-15-MP-4C363.[link](https://www.navymarinespeciesmonitoring.us/files/9315/3186/7492/Hanson_et_al_2018_Modeling_Occurrence_of_SRKW_in_NWTRC.pdf)

>15. Eguchi, T., C. Fahy, J. Jannot, K. Somers, and **E. Ward**. 2017. 2016 Leatherback sea turtle estimated bycatch reporting requirements as set out in the NMFS Biological Opinion for the continuing authorization of the Pacific Coast groundfish fisheries. National Marine Fisheries Service, SWFSC, La Jolla, CA 92039. [link](https://www.pcouncil.org/wp-content/uploads/2017/03/F5a_NMFS_Rpt3_ElectricOnly_Leatherback_Turtle_rpt_2017_Apr2017BB.pdf)

>14. Good, T. P., **E. Ward**, J. Jannot, R. Shama, N. Riley, and J. McVeigh. 2017. Observed and Estimated Bycatch of Short-tailed Albatross in U.S. West Coast Groundfish Fisheries 2014-2015. National Marine Fisheries Service, NWFSC, 2725 Montlake Blvd E., Seattle, WA 98112. (link)[https://www.pcouncil.org/wp-content/uploads/2017/03/F5a_NMFS_Rpt6_ElectricOnly_STAL_bycatch_report_2017_Apr2017BB.pdf]

>13. Gustafson, R., Y.-W. Lee, **E. Ward**, K. Somers, V. Tuttle, J. Jannot, and J. McVeigh. 2017. Observed and Estimated Bycatch of Eulachon in 2002–2015 US West Coast Groundfish Fisheries. National Marine Fisheries Service, NWFSC, 2725 Montlake Blvd E., Seattle, WA 98112. [link](https://www.pcouncil.org/wp-content/uploads/2017/03/F5a_NMFS_Rpt4_ElectricOnly_Eulachon_bycatch_rpt_2017_Apr2017BB.pdf)

>12. Lee, Y.-W., R. Gustafson, J. Jannot, J. McVeigh, N. Riley, K. Somers, V. Tuttle, S. Wang, and **E. Ward**. 2017. Observed and Estimated Bycatch of Green Sturgeon in 2002–2015 US West Coast Groundfish Fisheries. National Marine Fisheries Service, NWFSC, 2725 Montlake Blvd E., Seattle, WA 98112. [link](https://www.pcouncil.org/wp-content/uploads/2017/03/F5a_NMFS_Rpt5_ElectricOnly_Green_Sturgeon_Bycatch_rpt_2017_Apr2017BB.pdf)

>11. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2016 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>10. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2016 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>9. Gustafson, R.G., L. Weitkamp, Y.W. Lee, **E.J. Ward**, K. Somers, V. Tuttle, and J. Jannot. 2016. Status Review Update of Eulachon (Thaleichthys pacificus) Listed under the Endangered Species Act: Southern Distinct Population Segment. [link](http://www.westcoast.fisheries.noaa.gov/publications/status_reviews/other_species/eulachon/eulachon_2016_status_review_update.pdf)

>8. Gerrodette, T., **E.J. Ward**, R.L. Taylor, L.K. Schwarz, T. Eguchi, P.R. Wade, and G.K. Himes-Boor. 2016. Daniel Goodman’s empirical approach to Bayesian statistics. Pre-print at PeerJ [link](https://peerj.com/preprints/1755/)

>7. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2015 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>6. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2015 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>8. Eguchi, T., R. Bjorkland, C. Fahy, J. Jannot, T. Mitchell, K. Somers, **E. Ward**, B. Whiteside. 2015. Reporting requirements as set out in the NMFS Biological Opinion Leatherback sea turtles for the continuing authorization of the Pacific Coast groundfish fisheries. National Marine Fisheries Service, SWFSC, La Jolla, CA 92039. [link](http://www.pcouncil.org/wp-content/uploads/2015/06/D4_Sup_Att2_Turtle_Rpt_May2015Final_E-ONLY_JUN2015BB.pdf)

>7. Gustafson, R., Y.-W. Lee, **E. Ward**, K. Somers,V. Tuttle, J. Jannot. 2015. Observed and Estimated Bycatch of Eulachon in 2002–2013 US West Coast Groundfish Fisheries. National Marine Fisheries Service, NWFSC, 2725 Montlake Blvd E., Seattle, WA 98112. [link](http://www.pcouncil.org/wp-content/uploads/2015/06/D4_Sup_Att3_GF_BiOp_EulachonBycatchDoc_E-ONLY_JUN2015BB.pdf)

>6. Lee, Y.-W., R. Gustafson, J. Jannot, J. McVeigh, N. Riley, K. Somers, V. Tuttle, S. Wang, **E. Ward**. 2015.  The next link/button will exit from NWFSC web site Observed and Estimated Bycatch of Green Sturgeon in 2002–2013 US West Coast Groundfish Fisheries. National Marine Fisheries Service, NWFSC, 2725 Montlake Blvd E., Seattle, WA 98112. [link](http://www.pcouncil.org/wp-content/uploads/2015/06/D4_Sup_Att4_GreenSturgeonBiOpBycatchRpt_E-ONLY_JUN2015BB.pdf)

>5. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2014 Elwha River Steelhead Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>4. Denton, K., M. McHenry, R. Moses, **E.J. Ward**, M. Liermann, O. Stefankiv, W. Wells and G. Pess. 2014 Elwha River Chinook Escapement Estimate Based on DIDSON/ARIS Multi-Beam SONAR Data. Lower Elwha Tribe, Port Angeles, Washington.

>3. **E.J. Ward**, M.J. Ford, R.G. Kope, J.K.B. Ford, A. Velez-Espino, C.K. Parken, L. LaVoy, M.B. Hanson, K.C. Balcomb. Estimating the impacts of Chinook salmon abundance and prey removal by ocean fishing on Southern Resident killer whale population dynamics. 2013. U.S. Dept. Commer., NOAA Tech. Memo. NMFS-NWFSC-123, 71 p. [link](https://www.nwfsc.noaa.gov/assets/25/4647_08132013_113012_ImpactsOnSRKWsTM123WebFinal.pdf)

>2. Stout, H.A., P.W. Lawson, D.L. Bottom, T.D. Cooney, M.J. Ford, C.E. Jordan, R.G. Kope, L.M. Kruzic, G.R. Pess, G.H. Reeves, M.D. Scheuerell, T.C. Wainwright, R.S. Waples, **E.J. Ward**, L.A. Weitkamp, J.G. Williams, and T.H. Williams. 2012. Scientific conclusions of the status review for Oregon coast coho salmon (Oncorhynchus kisutch). U.S. Dept. Commer., NOAA Tech. Memo. NMFS-NWFSC-118, 242 p. [link](https://www.nwfsc.noaa.gov/assets/25/1916_08132012_121939_SROregonCohoTM118WebFinal.pdf)

>1. Northwest Fisheries Science Center. 2011. Risk assessment of U.S. West Coast groundfish fisheries to threatened and endangered marine species. NWFSC, NMFS. 2725 Montlake Blvd E, Seattle, WA. [link](https://www.nwfsc.noaa.gov/assets/11/4242_07142014_135038_Ford.et.al.2012.pdf)

# Book Chapters

**E.J. Ward** 2012. Population Dynamics. In *Grzimek’s Animal Life Encyclopedia*. pp. 195-
208.

# Teaching Experience

*FISH 507: Applied Time Series Analysis*, University of Washington \hfill 2012 - present
\newline Co-taught course with Eli Holmes and Mark Scheuerell [webpage](https://nwfsc-timeseries.github.io/)

*Ecological Society of America (ESA)* \hfill 2008 - 2011
\newline Co-taught Analysis of Multivariate Time-Series Data Using State-Space Models, and Introduction to MARSS

*NWFSC R workshop* (organized & taught) \hfill 2010 - 2011

*Visiting lecturer* University of Washington \hfill 2007 - 2009
\newline Taught FSH 497 Introductory modeling and programming course

# External Funding

**2019-2021** D. Finnoff, E.J. Ward, T. Miller, T. Schwoerer, M. Horning, D. Dugan. *Thresholds in a changing ocean environment: bioeconomic implications to inform adaptation decisions for Alaska’s salmon fisheries.* NOAA Ocean Acidification Program, $1,050,000.

**2018-2020** A.O. Shelton, J. Watson, C. Cunningham, E.J. Ward, A. Grey, M.J. Ford, K. Sommers. *Integrating Chinook Catches from Directed Fisheries and Trawl Bycatch to Improve Distribution Information for Bycatch Avoidance and Impacts On Predators in a Changing Environment.* NOAA Protected Species, $200K. 

**2018-2020** E.J. Ward, C. Harvey, J. Samhouri, etc. *Spatial ecosystem state and pressure indicators and scale-dependence of temporal indicator performance*. FATE (Fisheries And The Environment), $192K.

**2018-2020** M. Hunsicker, M. Litzow, E.J. Ward, B. Burke, S. Zador, C. Cunningham, and N. Bond. *Measuring the strength of ocean-atmosphere coupling to predict climate forcing of northeast Pacific ecosystems.* FATE (Fisheries And The Environment), $198K. 

**2018-2020** G. Holtgrieve, C. Harvey, and E.J. Ward. *Reconstructing a Century of Coastal Productivity and Predator Trophic Dynamics using Compound-specific Stable Isotopes from Archival Bone Specimens*. Washington Sea Grant, $192K.

**2018-2020** L. Hauser, B. Vadopalas, R. Childer, B. Hudson, B. Eudeline, and E.J. Ward. *Development of genetic risk assessment tools and Management Strategy Evaluation for Aquaculture of Native Shellfish*. Saltonstall-Kennedy Grant, $299K.

**2017-2018** E.J. Ward, G. Holtgrieve, C. Harvey. *Reconstructing a ecosystem productivity and marine mammal trophic dynamics using compound-specific stable isotopes from bone specimens*. NWFSC Internal Grants Program

**2016-2018** T.E. Essington, T.B. Francis, C. Greene, L. Kuehne, D. Lowry, E.J. Ward. *Recovering historical baselines in Puget Sound*. Washington Sea Grant, $243K.

**2016** E.J. Ward *Improving bycatch estimation through spatial statistics* $100K.

**2015** E.J. Ward, A.O. Shelton and M.J. Ford. *Portfolio Effects in Historic Chinook Hatchery Practices on Prey Availability for Southern Resident Killer Whales* National Fish and Wildlife Foundation, $110K.  

**2014-2015** I. Kaplan, E.J. Ward, et al. *A spatially explicit ecosystem model for quantifying marine mammal impacts on Chinook salmon* Pacific Salmon Commission Southern Fund, $206K.  

**2013-2014** T. Eguchi, E.J. Ward, and E.E. Holmes. *Developing risk assessment tools for marine sea turtles* $100K.

**2013-2014** Holmes, E.E. and E.J. Ward. *Developing web based computing tools for protected species*. $200K.

**2013** M.B. Hanson, E.J. Ward. et al. *Modeling the distribution of endangered killer whales in Pacific Northwest Navy ranges using acoustic recorder detections and satellite tagged whales*, US Navy. 

**2013** Shelton, A.O., E.J. Ward, J.T. Thorson, M. Bellman, B. Feist. *Integrating spatial habitat and fisheries effort data to improve abundance estimates of west coast groundfish*. $56K.

**2011** E.J. Ward et al., *Incorporating multiple data sources into a unified framework to improve estimates of adult salmon returns and population productivity*. $33K.

**2009** *NSF Comparative Analysis of Marine Ecosystem Organization: New statistical tools for analyzing community dynamics with applications to marine zooplankton*, $347K (141K from NCEAS). Associate Investigator (Principal Investigator - E.E. Holmes)

# Fellowships and Awards

**2006** *Cumulative Risk Assessment for Endangered Species* 2 year NRC post-doc awarded $92K.

**2003** *National Marine Fisheries Service / Washington Sea Grant Fellowship in Population Dynamics*: Incorporating model selection and decision analysis into population dynamics modeling. Grant awarded for $120K.

# Post-docs

**2012** Jim Thorson (NRC Research Post-doc). With Michelle McClure, Eli Holmes, and Mark Scheuerell  

**2012-2013** Guillaume Bal (NRC Research Post-doc). Co-supervised with Eli Holmes and Mark Scheuerell 

**2015-2017** Sean Anderson (Smith Fellow). Co-supervised with Trevor Branch

**2017-2019** Lewis Barnett (NWFSC) 

**2017--** Ben Nelson (NWFSC). Co-supervised with Ole Shelton

**2019--** Christian Commander (NWFSC) Co-supervised with Lewis Barnett

# Supervised Graduate	Students or	Committees

**2019--** Sam May (K. Naish), SAFS, University of Washington (NMFS Population Dynamics Fellowship)

**2017--** Natalie Lowell (L. Hauser), SAFS, University of Washington (NMFS Population Dynamics Fellowship)

**2017--** Megan Feddern (G. Holtgrieve), SAFS, University of Washington

**2017-2020** Elizabeth Ng (T. Essington), SAFS, University of Washington (NMFS Population Dynamics Fellowship)

**2012-2018** Pam Moriarty (T. Essington), SAFS, University of Washington

**2013-2016** Brandon Chasco (S. Heppell) Oregon State University (NMFS Population Dynamics Fellowship)

**2014-2015** Brian Stock (B. Semmens) SIO, with Tomo Eguchi

**2015-2016** Hannah Linder (J. Horne) UW

# Service and Outreach

**Subject Editor, Ecological Applications** \hfill 2013 - present  
  
**Puget Sound Seabird Survey** \hfill 2005-present
\newline Developed survey methodology for Puget Sound’s first land-based citizen science seabird survey and oversaw data analysis

**Orca Bowl** Washington State Sea Grant / University of Washington

**Secretary & Treasurer**, Statistical Ecology Section, Ecological Society of America 2010-2012
